In [29]:
import numpy as np

In [30]:
optimal_acc_np = np.load('./acc.npy')
file_list=np.load('./file_list.npy')

In [31]:
optimal_acc_np

array([0.8873, 0.8417, 0.8942, 0.7292, 0.9021, 0.8548, 0.8208, 0.7995,
       0.7664, 0.6984, 0.7346, 0.9014, 0.7218, 0.7278, 0.909 , 0.8625,
       0.7739, 0.7277, 0.915 , 0.8375, 0.9166, 0.8521, 0.8161, 0.9164,
       0.7667, 0.9136, 0.8765, 0.8394, 0.7676, 0.7081, 0.9102, 0.7629,
       0.8639, 0.6423, 0.9235, 0.8769, 0.8304, 0.7303, 0.9288, 0.7256,
       0.8636, 0.7758, 0.7541, 0.929 , 0.8769, 0.9352, 0.7531, 0.7515,
       0.7242, 0.9351, 0.7121, 0.8891, 0.8728, 0.8354, 0.7816, 0.7739,
       0.9327, 0.9264, 0.898 , 0.6833, 0.9368, 0.8596, 0.7261, 0.9337,
       0.6867, 0.9015, 0.8276, 0.7397, 0.7819, 0.7102, 0.9379, 0.834 ,
       0.859 , 0.8254, 0.739 , 0.9393, 0.7007, 0.9057, 0.8686, 0.7969,
       0.8003, 0.9308, 0.7432, 0.9311, 0.6896, 0.8937, 0.844 , 0.7059,
       0.9355, 0.8766, 0.7411, 0.934 , 0.6924, 0.8988, 0.8266, 0.9376,
       0.8053, 0.7013, 0.7026, 0.9356, 0.6723, 0.9097, 0.8875, 0.8478,
       0.7982, 0.7844, 0.9364, 0.9383, 0.7415, 0.9004, 0.6902, 0.9381,
      

In [32]:
max(optimal_acc_np)

0.9554

In [33]:
max_list=np.argmax(optimal_acc_np)
max_list

199

In [34]:
file_list[199]

'Continous_2weeks_57day_1term.xlsx'

In [35]:
x=np.sort(optimal_acc_np)[::-1]

In [36]:
x

array([0.9554, 0.9549, 0.9516, 0.9511, 0.9488, 0.948 , 0.947 , 0.9469,
       0.9461, 0.946 , 0.9459, 0.9449, 0.9448, 0.9446, 0.9445, 0.9439,
       0.9425, 0.9417, 0.9414, 0.941 , 0.9398, 0.9394, 0.9393, 0.9392,
       0.9389, 0.9388, 0.9383, 0.9383, 0.9381, 0.9379, 0.9379, 0.9379,
       0.9376, 0.9368, 0.9367, 0.9364, 0.9359, 0.9356, 0.9355, 0.9353,
       0.9352, 0.9352, 0.9352, 0.9351, 0.9349, 0.934 , 0.934 , 0.9337,
       0.9327, 0.9314, 0.9311, 0.9308, 0.929 , 0.9288, 0.9287, 0.9269,
       0.9264, 0.9257, 0.9255, 0.9235, 0.9223, 0.9206, 0.9206, 0.9196,
       0.9166, 0.9164, 0.9158, 0.9158, 0.915 , 0.9148, 0.9146, 0.9142,
       0.9136, 0.9135, 0.9132, 0.913 , 0.9124, 0.9102, 0.9097, 0.909 ,
       0.9073, 0.9063, 0.9057, 0.9054, 0.9042, 0.9021, 0.9015, 0.9014,
       0.9004, 0.8988, 0.898 , 0.8959, 0.8942, 0.8937, 0.8903, 0.8893,
       0.8891, 0.8875, 0.8873, 0.8858, 0.8856, 0.8835, 0.8821, 0.8811,
       0.8801, 0.8772, 0.8769, 0.8769, 0.8768, 0.8766, 0.8765, 0.8735,
      

In [37]:
for i in x:
    list_index=np.where(optimal_acc_np==i)
    print(file_list[list_index])

['Continous_2weeks_57day_1term.xlsx']
['Continous_2weeks_58day_1term.xlsx']
['Continous_2weeks_64day_1term.xlsx']
['Continous_2weeks_62day_1term.xlsx']
['Continous_2weeks_55day_1term.xlsx']
['Continous_2weeks_67day_1term.xlsx']
['Continous_2weeks_56day_1term.xlsx']
['Continous_2weeks_63day_1term.xlsx']
['Continous_2weeks_59day_1term.xlsx']
['Continous_2weeks_49day_1term.xlsx']
['Continous_2weeks_74day_1term.xlsx']
['Continous_2weeks_66day_1term.xlsx']
['Continous_2weeks_53day_1term.xlsx']
['Continous_2weeks_54day_1term.xlsx']
['Continous_2weeks_52day_1term.xlsx']
['Continous_2weeks_61day_1term.xlsx']
['Continous_2weeks_40day_1term.xlsx']
['Continous_2weeks_44day_1term.xlsx']
['Continous_2weeks_43day_1term.xlsx']
['Continous_2weeks_65day_1term.xlsx']
['Continous_2weeks_48day_1term.xlsx']
['Continous_2weeks_50day_1term.xlsx']
['Continous_2weeks_30day_1term.xlsx']
['Continous_2weeks_42day_1term.xlsx']
['Continous_2weeks_47day_1term.xlsx']
['Continous_2weeks_68day_1term.xlsx']
['Continous_

In [45]:
list_index=np.where(file_list=='Continous_2weeks_2day_1term.xlsx')
print(list_index)

(array([72], dtype=int64),)


In [46]:
optimal_acc_np[list_index]

array([0.859])

In [23]:
file_list.index(file_list[file_list=='Continous_2weeks_28day_8term.xlsx'])

AttributeError: 'numpy.ndarray' object has no attribute 'index'

In [57]:
list_index=np.where(file_list =='Continous_2weeks_2day_1term.xlsx')


optimal_acc_np[list_index]

array([0.7845])